### ISSUE TITLE
sles11sp3: Thruk fails when adding more than two backends

### ISSUE THREAD

**Issue by mittma** [sni/thruk_libs#4]
In the Apache log you can find the following error:
threads::shared version 1.21 required--this is only version 1.14 at /usr/lib64/thruk/perl5/Thread/Queue.pm line 9.

It works with updated Modules Threads and Threads::Shared

best regards,
Martin

**Comment by sni** [comment]
There was a discussion on the mailing list about this: https://groups.google.com/d/msg/thruk/-Y4u_CLWLOQ/ha26nc2yEQAJ
