### ISSUE TITLE
Please release 2.28

### ISSUE THREAD

**Issue by sshmanko** [sni/thruk_libs#6]
Thruk 2.28 doesn't work with 2.26 libs as:
`2019-04-15_07:48:41.97300 Error while loading /usr/local/thruk/share/script/thruk.psgi: Plack version 1.0046 required--this is only version 1.0045 at /usr/local/thruk/share/lib/Thrupackage Thruk::Request;
k/Request.pm line 4.`

**Comment by sni** [comment]
i forgot to push the 2.28 tag here, is that what you mean? Besides that, the packages have been released already.

**Comment by sshmanko** [comment]
yeah I couldn't find it under releases, sorry

**Comment by sni** [comment]
no worries, just pushed the missing tag. Thanks for reminding me.

**Comment by sshmanko** [comment]
thanks for fast response and amazing piece of software you develop 👍
